name: Publish Blog Drafts

on:
  schedule:
    - cron: '3 * * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Jekyll Publish Drafts
      uses: soywiz/github-action-jekyll-publish-drafts@v2
      with:
        github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
        jekyll_path: ./
        branch: master
